version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_2304_AWSSTAGEProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_2304_awsstage.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_2304_AWSSTAGEProject
    version: "1.0"
- serviceName: project.siqa_2304_awsstage.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_2304_AWSSTAGEProject
    version: "1.0"
